development:
  adapter: postgresql
  database: got-deadpool
  username: got-deadpool
  password: got-deadpool
  host: localhost

production:
  adapter: postgresql
  encoding: unicode
  pool: 5
  database: d87b23tpkt8s8s
  username:
  password:
  host: 
  port: 5432
